### ISSUE TITLE
Latest updates broke ntp on Raspberry Pi

### ISSUE THREAD

**Issue by nzapponi** [cturra/docker-ntp#35]
Hi,
I'm running your ntp Docker container on a Raspberry Pi, and the last update seems to have broken it.

Here are my logs:
```
ntp              | +588592596-05-04T01:24:56Z chronyd version 4.0 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER +SIGND +ASYNCDNS -NTS -SECHASH +IPV6 -DEBUG)
ntp              | +588384768-06-10T08:00:24Z Fatal error : clock_gettime() failed : Operation not permitted
ntp              | +624270944-01-21T11:54:16Z chronyd version 4.0 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER +SIGND +ASYNCDNS -NTS -SECHASH +IPV6 -DEBUG)
ntp              | +624063116-02-27T18:29:44Z Fatal error : clock_gettime() failed : Operation not permitted
ntp              | +695627639-07-24T16:14:32Z chronyd version 4.0 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER +SIGND +ASYNCDNS -NTS -SECHASH +IPV6 -DEBUG)
ntp              | +695419811-08-30T22:50:00Z Fatal error : clock_gettime() failed : Operation not permitted
```

... and it goes on and on.

Here's my `docker-compose.yml` setup:
```
ntp:
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    cap_add:
      - SYS_TIME
    read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    environment:
      - NTP_SERVERS=time.cloudflare.com
```

I tried both with and without the `SYS_TIME` privilege, no difference.

Any help would be appreciated!
