### ISSUE TITLE
Not working on Raspberry Pi

### ISSUE THREAD

**Issue by m0t0rh3ad** [cturra/docker-ntp#52]
Hello,
I've got cturra deployed on my Raspberry Pi server
My docker -compose file:
```
 services:
                  ntp:
                    build: .
                    image: cturra/ntp:latest
                    container_name: ntp
                    restart: always
                    ports:
                      - 123:123/udp
                    cap_add:
                      - SYS_TIME
                    read_only: true
                    tmpfs:
                      - /etc/chrony:rw,mode=1750
                      - /run/chrony:rw,mode=1750
                      - /var/lib/chrony:rw,mode=1750
                    environment:
                      - NTP_SERVERS="time1.google.com,time2.google.com,time3.google.com,time4.google.com"
                      - LOG_LEVEL=0
```
In logs I can see only this:
```
          2022-11-22T12:17:22Z chronyd version 4.1 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 -DEBUG)
            2022-11-22T12:17:22Z Disabled control of system clock
```
And NTP is not working. I've found in one of the issues that the problem can be with "libseccomp2", I've checked and found that "libseccomp2" is installed on my system.
Any suggestion?
