### ISSUE TITLE
Support for Ordoid C2 AARCH8 - firstly it worked but now it doesn't

### ISSUE THREAD

**Issue by DanielOberlechner** [cturra/docker-ntp#54]
Have you changed something in partikular or why won't the docker compose image not start anymore?

version: '3.4'

services:
  ntp:
    image: cturra/ntp-multiarch:latest
    container_name: ntp
    ports:
      - 123:123/udp
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    environment:
      - NTP_SERVERS=time.cloudflare.com,it.pool.ntp.org,time.google.com
    restart: always
`

**Comment by cturra** [comment]
looks like you're using an old image that i had created when i was testing out adding support for multiple architectures. that's been merged into the main image now for a long time. sorry for causing any confusion around that work.

can you try updating your `docker-compose` file to the following? that should get you back on track:

```yaml
version: '3.9'

services:
  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS=time.cloudflare.com,it.pool.ntp.org,time.google.com
      - LOG_LEVEL=0
```
