### ISSUE TITLE
sntp: Clock select failed

### ISSUE THREAD

**Issue by cksrc** [cturra/docker-ntp#67]
Bringing up the docker with the following docker compose service:
```
  local-ntp:
    image: cturra/ntp:latest
    container_name: local-ntp
    restart: always
    privileged: true
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS=time.google.com
      - LOG_LEVEL=0
      - TZ=Etc/GMT-4
```

When I try to query the NTP from my host (mac) with `sntp -d 192.168.176.2` I get

```
sntp: Exchange failed: Timeout
sntp_exchange {
        result: 6 (Timeout)
        header: 00 (li:0 vn:0 mode:0)
       stratum: 00 (0)
          poll: 00 (1)
     precision: 00 (1.000000e+00)
         delay: 0000.0000 (0.000000000)
    dispersion: 0000.0000 (0.000000000)
           ref: 00000000 ("    ")
         t_ref: 00000000.00000000 (0.000000000)
            t1: E8D89171.D7E4CD74 (3906507121.843334999)
            t2: 00000000.00000000 (0.000000000)
            t3: 00000000.00000000 (0.000000000)
            t4: 00000000.00000000 (0.000000000)
        offset: FFFFFFFF8B93B747.140D994600000000 (-1953253560.921667576)
         delay: FFFFFFFF17276E8E.281B328C00000000 (-3906507121.843335152)
          mean: 0000000000000000.0000000000000000 (0.000000000)
         error: 0000000000000000.0000000000000000 (0.000000000)
          addr: 192.168.176.2
}
sntp: Clock select failed
```
